export const DEFAULT_FLAVORS = [
  "Fancy Feast Classic Pâté – Chicken Feast",
  "Friskies Pâté – Turkey & Giblets Dinner",
  "Sheba Perfect Portions – Cuts in Gravy Roasted Chicken Entrée",
  "Purina Pro Plan – Savor Adult Chicken & Rice Entrée in Gravy",
  "Hill's Science Diet – Adult Tender Chicken Dinner",
  "Royal Canin – Feline Health Nutrition Instinctive Thin Slices in Gravy",
  "Blue Buffalo Wilderness – Chicken Grain-Free Pâté",
  "Wellness CORE – Grain-Free Turkey & Chicken Pâté",
  "Tiki Cat – Puka Puka Luau (Succulent Chicken in Chicken Consommé)",
  "Weruva – Paw Lickin' Chicken in Gravy",
  "Merrick Purrfect Bistro – Grain-Free Chicken Pâté",
  "Iams Perfect Portions – Cuts in Gravy Healthy Adult Chicken Recipe",
  "Nutro Perfect Portions – Grain-Free Real Chicken Pâté",
  "Applaws – Chicken Breast in Broth",
];
